name: (disabled) Jekyll deploy (manual only)

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Jekyll workflow disabled; using CRA Pages workflow in static.yml"
